language: python
python:
  - "3.6"
branches:
  only:
  - api
install:
  - pip install -r requirements.txt
script:
  - coverage run --omit */home/travis/virtualenv/* -m pytest
  - coverage report
  - coveralls
after success:
  -coveralls